// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hub_metadata.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHubMetadata = `-- name: CreateHubMetadata :one
INSERT INTO hub_metadata (singleton_id, hub_id, label)
VALUES (1, $1, $2)
RETURNING singleton_id, hub_id, label, created_at, updated_at
`

type CreateHubMetadataParams struct {
	HubID pgtype.UUID
	Label string
}

func (q *Queries) CreateHubMetadata(ctx context.Context, arg CreateHubMetadataParams) (HubMetadatum, error) {
	row := q.db.QueryRow(ctx, createHubMetadata, arg.HubID, arg.Label)
	var i HubMetadatum
	err := row.Scan(
		&i.SingletonID,
		&i.HubID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubMetadata = `-- name: GetHubMetadata :one
SELECT singleton_id, hub_id, label, created_at, updated_at
FROM hub_metadata
WHERE singleton_id = 1
`

func (q *Queries) GetHubMetadata(ctx context.Context) (HubMetadatum, error) {
	row := q.db.QueryRow(ctx, getHubMetadata)
	var i HubMetadatum
	err := row.Scan(
		&i.SingletonID,
		&i.HubID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHubMetadata = `-- name: UpdateHubMetadata :one
UPDATE hub_metadata
SET hub_id = $1,
    label = $2,
    updated_at = NOW()
WHERE singleton_id = 1
RETURNING singleton_id, hub_id, label, created_at, updated_at
`

type UpdateHubMetadataParams struct {
	HubID pgtype.UUID
	Label string
}

func (q *Queries) UpdateHubMetadata(ctx context.Context, arg UpdateHubMetadataParams) (HubMetadatum, error) {
	row := q.db.QueryRow(ctx, updateHubMetadata, arg.HubID, arg.Label)
	var i HubMetadatum
	err := row.Scan(
		&i.SingletonID,
		&i.HubID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
