// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fence struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	ForeignID pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Provider struct {
	ID        string
	Type      string
	Name      pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Trackable struct {
	ID        pgtype.UUID
	Type      string
	Name      pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Zone struct {
	ID        pgtype.UUID
	Type      string
	ForeignID pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
