// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	ListProviders(ctx context.Context) ([]Provider, error)
	ListZones(ctx context.Context) ([]Zone, error)
}

var _ Querier = (*Queries)(nil)
